twilio/twilio-video-app-react

README.md

- [x ] I acknowledge that all my contributions will be made under the project's license.
The readme contained an incorrect delete command, this should be twilio rtc:apps:video:delete
* [x ] Updated CHANGELOG.md if necessary
* [x ] Added unit tests if necessary
* [ x] Updated affected documentation
* [x ] Verified locally with `npm test`
* [x ] Manually sanity tested running locally
* [x ] Included screenshot as PR comment (if needed)
* [x ] Ready for review
* [x ] Re-tested if necessary

Correct app delete command

---

src/state/usePasscodeAuth/usePasscodeAuth.test.tsx
src/state/usePasscodeAuth/usePasscodeAuth.ts

- [AHOYAPPS-454](https://issues.corp.twilio.com/browse/AHOYAPPS-454)
This PR improves error handling for passcode auth. It handles the rare case when the user visits the Twilio Serverless URL before it expires, but then tries to join a room after it expires. It displays the same error messages that are seen on the passcode login screen.

Improve passcode error handling

---

README.md
package-lock.json
package.json
src/components/MainParticipantInfo/MainParticipantInfo.tsx
src/components/Participant/Participant.tsx
src/components/ParticipantInfo/ParticipantConnectionIndicator/ParticipantConnectionIndicator.tsx
src/components/ParticipantInfo/ParticipantInfo.tsx
src/components/ParticipantTracks/ParticipantTracks.tsx
src/hooks/useParticipantIsReconnecting/useParticipantIsReconnecting.ts
src/hooks/useParticipantNetworkQualityLevel/useParticipantNetworkQualityLevel.tsx
src/hooks/useScreenShareParticipant/useScreenShareParticipant.tsx

- [AHOYAPPS-452](https://issues.corp.twilio.com/browse/AHOYAPPS-452)
Some users were seeing typescript errors while building the app (which would stop the build). The errors would occur when version 3.8.3 of Typescript is used, but not when version 3.7.5 of Typescript is used. 
These users installed dependencies with `yarn` instead of `npm`. Yarn would ignore `package-lock.json` and it would install the newest major version of Typescript (3.8.3) as described by `package.json` instead of the version of TS that is specified in `package-lock.json` (3.7.5).
This PR updates TS to version 3.8.3 …

Typescript fix

---

src/hooks/useHeight/useHeight.test.tsx
src/hooks/useHeight/useHeight.ts
src/types.ts

- [AHOYAPPS-606](https://issues.corp.twilio.com/browse/AHOYAPPS-606)
This PR fixes a pinch-to-zoom issue in iOS Safari. When the user pinches to zoom in, the browser occasionally fires a `resize` event. Since the height of the app's main container is set dynamically with JS, these `resize` events break the layout because `window.innerHeight` shrinks as the user zooms in. 
This PR updates `useHeight` so that it takes the viewport's scale into account. This makes pinch-to-zoom work properly because the figure reported by `useHeight` will always stay the same as the user zooms:
innerHeight: …

Take visualViewport.scale into account when determining height of window

---

.circleci/config.yml
cypress/integration/twilio-video.spec.js
cypress/plugins/index.js
cypress/support/commands.js
src/components/AudioTrack/AudioTrack.tsx

- N/A
A while back, we changed the way that the AudioTrack component renders `<audio>` elements. This was done to try and fix a Safari bug, so we merged the change quickly and disabled the Cypress tests that broke. 
This PR re-enables those Cypress tests.

Fix cypress tests

---

src/hooks/useIsTrackEnabled/useIsTrackEnabled.test.tsx
src/hooks/useIsTrackEnabled/useIsTrackEnabled.tsx

- N/A
Fix a bug where the Mute Button shows that the audio is enabled when no track is present.
With this change, we will see the MicOff icon when no local audio track is present.

Fix useIsTrackEnabled

---

src/__mocks__/twilio-video.ts
src/components/VideoProvider/useLocalTracks/useLocalTracks.test.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts

- [AHOYAPPS-682](https://issues.corp.twilio.com/browse/AHOYAPPS-682)
This PR changes how permissions are requested. Now Firefox will request permissions only once. 
`ensureMediaPermissions` is no longer called before local tracks are created. `ensureMediaPermissions` is only used before `enumerateDevices` is called.
The `useLocalTracks` hook has been rewritten so that local audio and video are no longer requested separately. Now they are requested at the same time with `Video.createLocalTracks({audio: true, video: { ... }})`. 
This means that `getUserMedia` is called only once on …

Firefox media permission fix

---

src/components/Controls/ToggleVideoButton/ToggleVideoButton.test.tsx
src/components/Controls/ToggleVideoButton/ToggleVideoButton.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.test.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.tsx

- [AHOYAPPS-683](https://issues.corp.twilio.com/browse/AHOYAPPS-683)
This PR changes the logic of the publishing/unpublishing of the local video track in the following ways:
- The Mute Video button is now throttled so that it can only be clicked once every 200ms. This prevents issues caused by clicking the button excessively fast.
- The useLocalVideoToggle hook only publishes/unpublishes the local video track when it is not already doing so.
- If there is a publishing error, an error modal will be displayed instead of the app crashing. 
Resolves #218 and #233 
This PR can be manually tested …

Fix video publishing

---

src/components/MenuBar/ConnectionOptions/__snapshots__/ConnectionOptions.test.tsx.snap
src/state/settings/settingsReducer.test.ts
src/state/settings/settingsReducer.ts

- [AHOYAPPS-596](https://issues.corp.twilio.com/browse/AHOYAPPS-596)
This PR changes the default setting for max tracks to 10 for desktop browsers and 5 for mobile browsers.

Set max tracks based on browser

---

src/components/UnsupportedBrowserWarning/UnsupportedBrowserWarning.test.tsx
src/components/UnsupportedBrowserWarning/UnsupportedBrowserWarning.tsx
src/components/UnsupportedBrowserWarning/__snapshots__/UnsupportedBrowserWarning.test.tsx.snap
src/index.tsx

- [AHOYAPPS-515](https://issues.corp.twilio.com/browse/AHOYAPPS-515)
This PR adds a useful error message if the `isSupported` boolean is `true`. 
`isSupported` is always false when `window.isSecureContext` is false. In such cases we display the following text:
In cases where the browser is not supported, but the context is secure, the following error is displayed:
The link takes the user to our documentation: https://www.twilio.com/docs/video/javascript#supported-browsers

Ahoyapps 515 unsupported browsers

---

package-lock.json
package.json
src/__mocks__/twilio-video.ts
src/components/VideoProvider/index.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.test.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
src/hooks/useLocalVideoToggle/useLocalVideoToggle.test.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.tsx

- N/A
This PR updates the version of Twilio-video to 2.6.0. 
The Twilio-video SDK version 2.6.0 contains a fix for a known iOS Safari audio issue (see the [Changelog](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#260-june-26-2020)). This workaround requires that small parts of the React application be changed. Since it's possible that local tracks may be restarted by the SDK after a stopped event is fired, the React app must not remove local tracks from state when a stopped event is fired. Thus we remove the listeners in `useLocalTracks.tsx` (see …

Prepare app for twilio-video 2.6.0 upgrade

---

package-lock.json
package.json
src/components/AudioLevelIndicator/AudioLevelIndicator.tsx
src/components/LocalVideoPreview/LocalVideoPreview.test.tsx
src/components/MenuBar/DeviceSelector/AudioInputList/AudioInputList.tsx
src/components/MenuBar/DeviceSelector/VideoInputList/VideoInputList.tsx
src/components/MenuBar/FlipCameraButton/FlipCameraButton.test.tsx
src/components/MenuBar/FlipCameraButton/FlipCameraButton.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
src/components/VideoTrack/VideoTrack.test.tsx
src/components/VideoTrack/VideoTrack.tsx
src/constants.ts
src/hooks/useIsTrackEnabled/useIsTrackEnabled.test.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.test.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.tsx
src/hooks/useMediaStreamTrack/__mocks__/useMediaStreamTrack.ts
src/hooks/useMediaStreamTrack/useMediaStreamTrack.test.ts
src/hooks/useMediaStreamTrack/useMediaStreamTrack.ts
src/types.ts

- [AHOYAPPS-734](https://issues.corp.twilio.com/browse/AHOYAPPS-734)
This PR upgrades twilio-video to 2.7.0 and implements the new `track.restart()` feature.  The `track.restart()` feature allows users to change the constraints of their local audio and video tracks without the hassle of unpublishing and republishing the tracks to/from the room.
The `track.restart()` feature replaces publish/unpublish logic in the `AudioInputList`, `VideoInputList`, and `FlipCameraButton` components. 
Additionally, the `VideoTrack` and `AudioLevelIndicator` components had to be updated because they rely on …

Ahoyapps 734 add track restart feature

---

src/components/AudioLevelIndicator/AudioLevelIndicator.tsx

- N/A
This PR fixes a small issue with the AudioLevelIndicator component. Occasionally it does not respond to changes in volume, even though the other participants in the room can hear your audio. This change fixes that, and it also fixes an issue where the indicator does not respond if the AudioLevelIndicator component is instantiated while the LocalAudioTrack is disabled. It also now stops all cloned media tracks when the user mutes their audio.

Audio indicator fix

---

package-lock.json
package.json

-N/A
Update twilio-video to version 2.7.2

Update twilio-video to version 2.7.2

---

README.md

Added a section in the readme to explain how the different room types affect the app's behavior.

AHOYAPPS-871: Document video app room type behavior

---

src/components/Buttons/ToggleVideoButton/ToggleVideoButton.test.tsx
src/components/Buttons/ToggleVideoButton/ToggleVideoButton.tsx

- NA
This PR increases the throttle interval in the ToggleVideoButton component. This should help to solve the issue described in https://github.com/twilio/twilio-video-app-react/issues/262

Increase throttle interval in ToggleVideoButton component

---

src/components/VideoProvider/useSelectedParticipant/useSelectedParticipant.test.tsx
src/components/VideoProvider/useSelectedParticipant/useSelectedParticipant.tsx

- [AHOYAPPS-912](https://issues.corp.twilio.com/browse/AHOYAPPS-912)
This PR updates the `useSelectedParticipant` hook so that it listens to the `participantDisconnected` event. Now, when a participant leaves the room, they will be unpinned. 
Fixes #338

Unpin participant when they disconnect from room

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR bumps the app version to 0.2.1 and adds a changelog entry. It also upgrades the `twilio-video` version.

Release 0.2.1

---

src/components/ParticipantInfo/ParticipantInfo.tsx
src/components/ParticipantList/ParticipantList.tsx
src/components/Room/Room.tsx
src/theme.ts

- [AHOYAPPS-908](https://issues.corp.twilio.com/browse/AHOYAPPS-908)
This PR adjusts some CSS so that participant thumbnails are visible on mobile devices in landscape orientation:
Previously, the main video would expand vertically, pushing the thumbnails out of view. That no longer happens.

Fix video sizing on mobile landscape

---

src/components/PreJoinScreens/PreJoinScreens.test.tsx
src/components/PreJoinScreens/PreJoinScreens.tsx

- N/A
This fixes a bug where `getAudioAndVideoTracks` is called repeatedly when there is a `getUserMedia` error. The repeated calls to `getAudioAndVideoTracks` result in the error message never being displayed to the user.

Fix bug where getAudioAndVideoTracks was repeatedly called

---

src/hooks/useVideoTrackDimensions/useVideoTrackDimensions.test.tsx
src/hooks/useVideoTrackDimensions/useVideoTrackDimensions.tsx

- N/A
This pull request contains a bugfix submitted by Github user @tomhicks. I've pulled his changes into a new PR so that the Circle CI tests can run on it. Here is the original PR: https://github.com/twilio/twilio-video-app-react/pull/376
This PR fixes an issue found in the `useDimensionsChanged` hook, where the `handleDimensionsChanged` function would set the same object reference as the one already stored in the hook's state. This means that component that use this hook would not re-render when a track's dimensions have changed. 
`handleDimensionsChanged` now returns a new object …

Update useDimensionsChanged hook so that it causes re-render

---

src/components/ParticipantList/ParticipantList.tsx
src/components/ParticipantList/__snapshots__/ParticipantList.test.tsx.snap

- N/A
This PR fixes the flicker that is sometimes seen in the participant sidebar when the browser window just short enough to make the scrollbar appear. 
Before:
After:
The flicker is caused by a CSS infinite loop. When the scrollbar appears in the sidebar, it reduces the width of the participant thumbnails, which reduces their height (to preserve aspect ratio), which reduces the length of the list, which removes the scroll bar, which increases the width of the participant thumbnails, which increases their length, and so on.
This fix adds an additional div in the sidebar (the …

Fix sidebar flicker

---

src/__mocks__/twilio-video.ts
src/components/DeviceSelectionDialog/VideoInputList/VideoInputList.test.tsx
src/components/DeviceSelectionDialog/VideoInputList/VideoInputList.tsx
src/components/PreJoinScreens/DeviceSelectionScreen/SettingsMenu/SettingsMenu.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.test.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
src/hooks/useLocalVideoToggle/useLocalVideoToggle.test.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.tsx

- [AHOYAPPS-980](https://issues.corp.twilio.com/browse/AHOYAPPS-980)
This PR fixes an issue where the app crashes when the user tries to change their selected video device when their camera is off.  Now the user can change video devices while their video is off. This works before you join a room, and while you are in a room.
This PR also fixes the alignment of the settings menu that you see in the gif here.
Closes #389

Ahoyapps 980 switch camera crash fix

---

src/index.tsx

- N/A
This PR fixes an issue where the UnsupportedBrowserWarning is not displayed on devices where `Video.isSupported` is `false` and `navigator.mediaDevices` doesn't exist (like older iPhones). 
The `<UnsupportedBrowserWarning>` component needs to wrap the `<AppStateProvider>` component. The `<AppStateProvider>` uses the `useActiveSinkId` hook, which uses the `useDevices` hook, which attempt to access properties of `navigator.mediaDevices`. This change prevents `navigator.mediaDevices` from being access when it doesn't exist.
This change prevents the error that is seen in issue #439.

Move UnsupportedBrowserWarning

---

src/components/Buttons/EndCallButton/EndCallButton.test.tsx
src/components/Buttons/EndCallButton/EndCallButton.tsx
src/components/VideoProvider/index.test.tsx
src/components/VideoProvider/index.tsx
src/components/VideoProvider/useHandleRoomDisconnection/useHandleRoomDisconnection.test.tsx
src/components/VideoProvider/useHandleRoomDisconnection/useHandleRoomDisconnection.ts
src/components/VideoProvider/useScreenShareToggle/useScreenShareToggle.test.tsx
src/components/VideoProvider/useScreenShareToggle/useScreenShareToggle.tsx

- [VIDEO-4365](https://issues.corp.twilio.com/browse/VIDEO-4365)
This PR stops all tracks (audio, video, and screen share) when the user is disconnected from the room for any reason (network disconnection, or clicking the 'Disconnect' button). Previously, the tracks were only stopped when the user clicked on the Disconnect button.
Resolves #444

Stop screensharing on disconnect

---

package.json
src/components/Buttons/ToggleChatButton/ToggleChatButton.test.tsx
src/components/Buttons/ToggleChatButton/ToggleChatButton.tsx

- [VIDEO-3733](https://issues.corp.twilio.com/browse/VIDEO-3733)
This PR adds a notification to the Chat button in the menu, to let the user know when there are unread messages in the chat window. It also displays an animated 'blip' when each new message is received. When the user opens the chat window, the notification is cleared. The notification is not shown when new messages are received while the chat window is opened.
Here's a gif of three messages being received while the chat window is closed. Then, the chat button is clicked to open the chat window which clears the notification:

Chat notification

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR prepares the release of version 0.2.4 of the app. See updated changelog here: https://github.com/twilio/twilio-video-app-react/blob/release-0.2.4/CHANGELOG.md

Release version 0.2.4

---

src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.test.tsx
src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx

- [VIDEO-4525](https://issues.corp.twilio.com/browse/VIDEO-4525)
This PR adds a loading spinner while a participant is connecting to a room as it takes a second or two longer to join due to the addition of the new conversations feature. 
**Note**, because this spinner shows if either `isFetching` or `isConnecting` is true, the screen with the `Join Now` button is replaced by the loading screen. Therefore, I had to remove the following test from `describe('when connecting a room', () => {...})` and `describe('when fetching a token', () => {...})`:
` it('should disable the Join Now button', …

Video 4525 loading screen

---

src/components/ChatWindow/MessageList/MessageList.test.tsx
src/components/ChatWindow/MessageList/MessageList.tsx
src/components/ChatWindow/MessageList/__snapshots__/MessageList.test.tsx.snap

- N/A
This PR changes how `MessageInfo` components are displayed in the `MessageList` component. Instead of displaying a `MessageInfo` component whenever a message has a new author, `MessageInfo` components are now displayed when a message has a new author or formatted timestamp.

Update MessageList component to change how messages are grouped

---

LICENSE
README.md

- N/A
This PR adds some additional context to the README about the new chat feature. You can see the formatted README here: https://github.com/twilio/twilio-video-app-react/tree/conversations-documentation-updates
(apologies about all the changes. I forgot to disable my automatic formatter for this file.)

Update readme with info about twilio conversations

---

src/components/VideoProvider/index.test.tsx
src/components/VideoProvider/index.tsx
src/components/VideoProvider/useRestartAudioTrackOnDeviceChange/useRestartAudioTrackOnDeviceChange.test.tsx
src/components/VideoProvider/useRestartAudioTrackOnDeviceChange/useRestartAudioTrackOnDeviceChange.ts

- [VIDEO-4739](https://issues.corp.twilio.com/browse/VIDEO-4739)
This PR fixes the bug addressed in GitHub Issue #462.
When a user is connected to a room and uses an external microphone (or headphones with a built-in microphone), and then disconnects that mic, the other participants can no longer hear the user despite being unmuted. We fixed this bug by adding a new hook (`useRestartAudioTrackOnDeviceChange()`) to the `VideoProvider`. This hook restarts the local audio track whenever there is a device change event **and** the track's `mediaStreamTrack.readyState` is equal to`ended`.

Video 4601 fix audio input device

---

src/utils/useConnectionOptions/useConnectionOptions.test.tsx
src/utils/useConnectionOptions/useConnectionOptions.ts

- [VIDEO-4739](https://issues.corp.twilio.com/browse/VIDEO-4739)
This PR fixes the bug addressed in #474.
This PR adds the key-value pair `trackSwitchOffMode: settings.trackSwitchOffMode` to the `connectionOptions` object in the `useConnectionOptions` hook as it was previously missing.

Video 4739 add track switch off mode to connection options

---

src/components/MainParticipantInfo/MainParticipantInfo.tsx
src/components/NetworkQualityLevel/NetworkQualityLevel.tsx
src/components/NetworkQualityLevel/__snapshots__/NetworkQualityLevel.test.tsx.snap
src/components/ParticipantInfo/ParticipantInfo.tsx

- [VIDEO-4893](https://issues.corp.twilio.com/browse/VIDEO-4893)
This PR adds the network quality indicator to the main participant. This is the same network quality indicator that is used by the `<ParticipantInfo />` component. We decided to move the styling to the `<NetworkQualityLevel />` in order to remove the empty boxes from the participant thumbnails in P2P rooms. 
GitHub issue: #490 
Screenshots:
**Main participant === localParticipant:**
**Main participant !== localParticipant:**

Video 4893 show network for main participant

---

src/components/VideoProvider/useRestartAudioTrackOnDeviceChange/useRestartAudioTrackOnDeviceChange.test.tsx
src/components/VideoProvider/useRestartAudioTrackOnDeviceChange/useRestartAudioTrackOnDeviceChange.ts

- N/A
This PR addresses a follow-up bug to GitHub issue #462. In Firefox, when a user is connected to a room and uses an external microphone (or headphones with a built-in microphone), and then disconnects that mic, the other participants can no longer hear the user despite being unmuted. We fixed this by passing an empty object `{}` to `audioTrack.restart()` in the `useRestartAudioTrackOnDeviceChange` hook, which will use the default `MediaTrackConstraints` as a result.

add empty object as constraints parameter for restart method

---

src/components/ChatWindow/ChatInput/ChatInput.test.tsx
src/components/ChatWindow/ChatInput/ChatInput.tsx
src/components/ChatWindow/ChatWindow.tsx

- N/A
This PR fixes the styling of the chat input in firefox. The input now has a consistent appearance across all browsers. In Chrome and Safari, the appearance has not changed from how it looked previously. 
Firefox: 
To see what it looked like previously, see this issue: https://github.com/twilio/twilio-video-app-react/issues/498

Fix firefox styling of textarea element

---

package-lock.json
src/__mocks__/twilio-video.ts
src/components/VideoProvider/useLocalTracks/useLocalTracks.test.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
src/hooks/useDevices/useDevices.test.tsx
src/hooks/useDevices/useDevices.tsx
src/utils/index.test.ts
src/utils/index.ts

- N/A
This pull request removes the usage of the `useDevices` hook from the `useLocalTracks` hook. 
The values in the `useDevices` hook are not updated after a user grants permission to their microphone and camera. Because of this, the values returned by `useDevices` can be stale by the time they are used in the callbacks inside `useLocalTracks`. 
This issue is solved by calling `enumerateDevices` at the beginning  of the execution of the `useLocalTracks` callbacks. With this, the device information is never stale.
Resolves: #425

Remove usedevices from uselocaltracks

---

src/components/MenuBar/Menu/Menu.test.tsx
src/components/MenuBar/Menu/Menu.tsx
src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.test.tsx
src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx
src/state/index.test.tsx
src/state/index.tsx
src/state/useFirebaseAuth/useFirebaseAuth.ts
src/state/usePasscodeAuth/usePasscodeAuth.test.tsx
src/state/usePasscodeAuth/usePasscodeAuth.ts

- N/A
This PR adds logic so that the recording start/stop button isn't rendered when the room type is peer-to-peer or go. 
Additionally, some of the token request logic in src/state was modified so that the roomType is saved no matter which authentication scheme is used. 
If the roomType is ever unknown (a developer using their own server that isn't properly set up), then the recording button will be rendered. If the room type doesn't allow recording, the user will see a useful error message:

Conditionally render recording rules button

---

src/__mocks__/twilio-video.ts
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts

- N/A
This PR fixes an issue where users are unable to acquire audio in Firefox due to an error. 
This PR removes the usage of `mediaStreamStrack.getCapabilities()` and replaces it with `mediaStreamStrack.getSettings()`. These functions are used to get the deviceID after a camera track is acquired. 
The error was due to the fact that `getCapabilities()` is not supported in Firefox. See the following browser compatibility tables:
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getSettings
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities
This …

Use getSettings instead of getCapabilities to fix FF error

---

src/components/PreJoinScreens/MediaErrorSnackbar/MediaErrorSnackbar.test.tsx
src/components/PreJoinScreens/MediaErrorSnackbar/MediaErrorSnackbar.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.test.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
src/utils/index.test.ts
src/utils/index.ts

- [VIDEO-4206](https://issues.corp.twilio.com/browse/VIDEO-4206)
This PR improves the device error handling on the Device Selection Screen. It fixes an issue where the microphone was not acquired when the camera permissions were disabled. 
Now the user can explicitly deny just their camera or microphone permissions and the app will function as expected. The app will display warnings to the user if they have denied any device permissions. 
Resolves #428 
Camera still works when microphone permissions are denied: 
Microphone still works when camera permissions are denied: 
Update: Handle …

Improve device errors

---

package-lock.json
package.json
src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.test.tsx
src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.ts

- [VIDEO-5735](https://issues.corp.twilio.com/browse/VIDEO-5735)
Added virtual background feature

VIDEO-5735/Add virtual background feature

---

src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.ts

- [VIDEO-6368](https://issues.corp.twilio.com/browse/VIDEO-6368)
Wait to load images for virtual background before removing the processor

VIDEO-6368 | wait to load image before removing processor

---

src/components/ChatProvider/index.tsx
src/components/MainParticipantInfo/MainParticipantInfo.test.tsx
src/components/MainParticipantInfo/MainParticipantInfo.tsx
src/components/ParticipantInfo/ParticipantInfo.test.tsx
src/components/ParticipantInfo/ParticipantInfo.tsx
src/components/ParticipantTracks/ParticipantTracks.test.tsx
src/components/ParticipantTracks/ParticipantTracks.tsx
src/components/PreJoinScreens/DeviceSelectionScreen/LocalVideoPreview/LocalVideoPreview.test.tsx
src/components/PreJoinScreens/DeviceSelectionScreen/LocalVideoPreview/LocalVideoPreview.tsx
src/components/Publication/Publication.test.tsx
src/components/Publication/Publication.tsx
src/components/VideoProvider/index.tsx
src/hooks/useFlipCameraToggle/useFlipCameraToggle.test.tsx
src/hooks/useFlipCameraToggle/useFlipCameraToggle.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.test.tsx
src/hooks/useLocalVideoToggle/useLocalVideoToggle.tsx
src/setupTests.ts

- [AHOYAPPS-6578](https://issues.corp.twilio.com/browse/AHOYAPPS-6578)
This PR addresses an interoperability issue between this app and Twilio's iOS and Android quickstart apps. The issue was that this app was not displaying video tracks because the tracks were not correctly labeled. If the track name did not include 'camera' (all lowercase), then the track would not be displayed. This means that unlabeled tracks, or tracks labeled as 'Camera' (uppercase 'C') would not be displayed. 
This PR removes the requirement that video tracks have a name in order to be displayed. Screen share tracks …

Video 6578 display all camera tracks

---

src/components/DeviceSelectionDialog/AudioInputList/AudioInputList.test.tsx
src/components/DeviceSelectionDialog/VideoInputList/VideoInputList.test.tsx
src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.ts
src/hooks/useLocalStorageState/useLocalStorageState.test.ts
src/hooks/useLocalStorageState/useLocalStorageState.ts
src/setupTests.ts
src/state/index.tsx

- [VIDEO-10096](https://issues.corp.twilio.com/browse/VIDEO-10096)
This PR updates the app so that the settings related to Grid Mode are persisted between visits (using local storage). A new hook, `useLocalStorageState` was created so that we don't have to duplicate the same local storage local throughout the app. This hook was also added to the `useBackgroundSettings` hook to simplify it a little.

Video 10096 persist grid settings

---

src/components/Room/Room.test.tsx
src/components/Room/Room.tsx

- [VIDEO-10095](https://issues.corp.twilio.com/browse/VIDEO-10095)
This PR adds some logic to the app which switches the user to the Collaboration View when a remote participant (but not the local participant) starts to share their screen. Without this, a user using Grid View would not know that someone else is sharing their screen. Once the user has been automatically switched over to Grid View, they are free to switch back to Collaboration View. 
This is the same behavior as what is already implemented in the iOS Video App: https://github.com/twilio/twilio-video-app-ios/blob/67b8494a50eb48 …

Handle screenshare in grid mode

---

src/components/VideoTrack/VideoTrack.test.tsx
src/components/VideoTrack/VideoTrack.tsx

This helps to workaround a Safari CSS issue related to transforms
- [VIDEO-9871](https://issues.corp.twilio.com/browse/VIDEO-9871)
This PR changes the way that the local video track is mirrored. This change is made to help an issue that is experienced in Desktop Safari where the local video track sometimes appears to be black.
This changes the CSS:
`transform: rotateY(180deg)`
Which computes to (as seen in the 'Computed' tab in DevTools): 
`transform: matrix3d(-1, 0, -1.2246467991473532e-16, 0, 0, 1, 0, 0, 1.2246467991473532e-16, 0, -1, 0, 0, 0, 0, 1);`
to:
`transform: scaleX(-1)`
Which …

Update CSS for mirroring local video

---

src/components/DeviceSelectionDialog/DeviceSelectionDialog.tsx
src/components/GridView/GridView.test.tsx
src/components/GridView/GridView.tsx
src/components/MobileGridView/MobileGridView.test.tsx
src/components/MobileGridView/MobileGridView.tsx
src/components/MobileGridView/__snapshots__/MobileGridView.test.tsx.snap
src/components/ParticipantInfo/ParticipantInfo.tsx
src/components/ParticipantList/ParticipantList.test.tsx
src/components/ParticipantList/ParticipantList.tsx
src/components/ParticipantProvider/index.tsx
src/hooks/useGridLayout/useGridLayout.ts
src/hooks/useParticipantsContext/useParticipantsContext.ts
src/index.tsx
src/theme.ts

- [VIDEO-10220](https://issues.corp.twilio.com/browse/AHOYAPPS-0000)
This PR addresses some feedback received during the dogfooding session for Grid View:
- Hides Grid View settings when on mobile 
- Adds a `<ParticipantProvider />` so that the presentation participants and grid participants do not re-render when users switch between Grid and Presentation View. This helps preserve the ordering of the dominant speakers as users switch between views.
- Adds styling for landscape mode for mobile devices so that it is consistent with iOS. Note, I included the custom breakpoint from the …

Dogfood feedback

---

src/components/AudioLevelIndicator/AudioLevelIndicator.tsx

- [VIDEO-10214](https://issues.corp.twilio.com/browse/VIDEO-10214)
This PR fixes an issue where the AudioLevelIndicator can cause a memory leak after it is mounted/unmounted many times. 
To see the issue, join a room, and run this code in the console which will repeatedly click the "Mute Audio" button:
```
var intervalId = setInterval(() => document.querySelector('[data-cy-audio-toggle]').click(), 10);
```
To stop this, just clear the interval id:
```
clearInterval(intervalId);
```
As the local audio track is repeatedly muted and unmuted, it will cause the AudioLevelIndicator to turn on and …

Fix memory leak in AudioLevelIndicator

---

src/components/AudioLevelIndicator/AudioLevelIndicator.tsx

This PR contains a workaround for a bug introduced in Chrome 103, where calling .stop() on a cloned MediaStreamTrack can cause a loss of audio in the app. This PR updates the AudioLevelIndicator component to only clone MediaStreamTracks on iOS, as this is the only instance where it is necessary to do so.
More information can be found in this github issue: https://github.com/twilio/twilio-video.js/issues/1811

Do not clone MediaStreamTrack in Chrome

---

CHANGELOG.md
package-lock.json
package.json

This PR adds CHANGELOG entry and updates version to `0.7.0` to release gallery view feature.

prep release

---

.circleci/config.yml
CHANGELOG.md
package-lock.json
package.json

For some reason, when we download the service account credentials, it is stored in the following format:
```
{
...
}
some-hex-number
```
This results in the application server's JSON parser failing to parse the credentials. So, this PR fixes the problem by removing the hexadecimal number from the output.

Store gcloud service account credentials in proper JSON format.

---

CHANGELOG.md
package-lock.json
package.json
src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.test.tsx
src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.ts
src/constants.ts

- [VIDEO-12945](https://issues.corp.twilio.com/browse/VIDEO-12945)
* Upgrade `twilio-video` to 2.27.0.
* Upgrade `@twilio/video-processors` to 2.0.0.
* Debounce is disabled for desktop Chrome.
* On desktop Chrome and browsers not supporting SIMD, switch to 640x480 when BackgroundProcessor is added.

VIDEO-12945 Upgrade to twilio-video@2.27.0 and @twilio/video-processors@2.0.0

---

CHANGELOG.md
package-lock.json
package.json

twilio-video.js@2.28.0
