twilio/twilio-video-app-react

.circleci/config.yml
.env.example
package.json
src/components/Controls/useIsUserActive/useIsUserActive.ts
src/components/LoginPage/LoginPage.test.tsx
src/components/LoginPage/LoginPage.tsx
src/components/MenuBar/Menu/Menu.test.tsx
src/components/MenuBar/Menu/Menu.tsx
src/components/MenuBar/MenuBar.test.tsx
src/components/MenuBar/MenuBar.tsx
src/components/PrivateRoute/PrivateRoute.test.tsx
src/components/PrivateRoute/PrivateRoute.tsx
src/state/index.test.tsx
src/state/index.tsx
src/state/useFirebaseAuth/useFirebaseAuth.test.ts
src/state/useFirebaseAuth/useFirebaseAuth.ts
src/state/usePasscodeAuth/usePasscodeAuth.test.ts
src/state/usePasscodeAuth/usePasscodeAuth.test.tsx
src/state/usePasscodeAuth/usePasscodeAuth.ts

- [AHOYAPPS-338](https://issues.corp.twilio.com/browse/AHOYAPPS-338)
This PR adds passcode auth to the video app. It can be enabled at build time with an environment variable:
`REACT_APP_SET_AUTH=passcode`
Firebase auth is still available:
`REACT_APP_SET_AUTH=firebase`
This passcode auth is meant to be used with a Twilio Function that can be deployed using a Twilio CLI Plugin currently in development. 
These screens ^ are only visible if the passcode is not present in the URL. 
http://my-video-url.com/?passcode=1234567890

Ahoyapps 338 community variant

---

src/hooks/useScreenShareToggle/useScreenShareToggle.test.tsx
src/hooks/useScreenShareToggle/useScreenShareToggle.tsx

- N/A
Sets screen share tracks to be published with high priority.

Publish screen share tracks with high priority

---

README.md

https://issues.corp.twilio.com/browse/AHOYAPPS-435
1. The really obvious changes to make are grouped in the first commit.
1. Not so obvious changes were done in separate commits so they are itemized and can be reverted if necessary. See commit message for description of what changed and why.
1. I will make comments for other changes I didn't think I should make myself without discussion.
1. I used `shield` style for CircleCI badge because that is what Ryan used for iOS readme and it seems more popular on GitHub.
1. I didn't add more screenshots besides the main app screenshot because nothing that would add value came to mind and they are difficult to maintain.

AHOYAPPS-435: Readme consistency

---

src/components/Controls/ToogleScreenShareButton/ToggleScreenShareButton.test.tsx
src/components/Controls/ToogleScreenShareButton/ToggleScreenShareButton.tsx

- N/A
This branch was created so that the CircleCI jobs would run. See original PR from forked repo: https://github.com/twilio/twilio-video-app-react/pull/92

Fix get display media issue

---

package-lock.json
package.json

N/A
This PR uses cross-env to set environment variables in a way that will work on any platform (linux, windows).  I have manually tested this in Windows and it works.

Use cross-env to set environment variables in NPM scripts

---

src/components/MenuBar/MenuBar.test.tsx
src/components/MenuBar/MenuBar.tsx
src/state/index.test.tsx
src/state/index.tsx

- [AHOYAPPS-331](https://issues.corp.twilio.com/browse/AHOYAPPS-331)
This PR sets an `isFetching` variable to true while the token is being fetched.  This is used to disable the Join Room button and display the loading spinner seen in the menu.

Ahoyapps 331 join room bug

---

package-lock.json
package.json

-N/A
This PR prevents incorrect instructions from being printed to the console after `npm run build` in run.

Fix build message

---

README.md

N/A
Adds install instructions to the readme. Resolves: https://github.com/twilio/twilio-video-app-react/issues/108

Update install instructions in readme

---

.env.example

- N/A
This PR adds clearer instructions to `.env.example`.  Resolves https://github.com/twilio/twilio-video-app-react/issues/117

Clarify instructions in .env.example

---

cypress/integration/twilio-video.spec.js
src/components/AudioTrack/AudioTrack.test.tsx
src/components/AudioTrack/AudioTrack.tsx

Update how audio track renders

---

src/components/Controls/Controls.tsx

- N/A
Resolves #113
`max-width: min-content` compatibility across browsers:
https://caniuse.com/#feat=mdn-css_properties_max-width_min-content

fix controls shift position on hover in Safari issue #113

---

cypress/integration/twilio-video.spec.js
src/components/AudioLevelIndicator/AudioLevelIndicator.test.tsx
src/components/AudioLevelIndicator/AudioLevelIndicator.tsx
src/components/AudioTrack/AudioTrack.tsx
src/components/MenuBar/LocalAudioLevelIndicator/LocalAudioLevelIndicator.tsx
src/components/MenuBar/MenuBar.test.tsx
src/components/MenuBar/MenuBar.tsx
src/components/MenuBar/ToggleFullScreenButton/ToggleFullScreenButton.test.tsx
src/components/MenuBar/ToggleFullScreenButton/ToggleFullScreenButton.tsx
src/components/ParticipantInfo/ParticipantInfo.test.tsx
src/components/ParticipantInfo/ParticipantInfo.tsx
src/components/VideoProvider/useRoom/useRoom.tsx

- [AHOYAPPS-514](https://issues.corp.twilio.com/browse/AHOYAPPS-514)
This PR adds:
- Passing `?customIdentity=true` will allow users to edit their Identity when using firebase auth (very useful for testing)
- Exposes `Video` object as `window.TwilioVideo`
- Adds an Audio Level Indicator component to the menubar, which lets users visually verify that their microphone is working before they join a room
- Adds Audio Level Indicators to each participant. It shows their audio level, which is useful to see who is speaking, and it's also useful for finding audio issues. The Audio indicator also …

Audio track render

---

src/components/VideoProvider/useLocalTracks/useLocalTracks.test.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts

- N/A
This PR updates useLocalTrack so that the browser request audio and video permissions at the same time. Previously the app requested audio and video in two separate requests.

Update media permission request

---

src/components/ParticipantTracks/ParticipantTracks.test.tsx
src/components/ParticipantTracks/ParticipantTracks.tsx
src/components/ParticipantTracks/__snapshots__/ParticipantTracks.test.tsx.snap
src/hooks/useScreenShareParticipant/useScreenShareParticipant.tsx

Fix screenshare regression

---

src/components/LoginPage/LoginPage.tsx
src/components/Room/Room.tsx

- [AHOYAPPS-605](https://issues.corp.twilio.com/browse/AHOYAPPS-605)
This PR fixes https://github.com/twilio/twilio-video-app-react/issues/178
It also fixes a FF issue with the 'Paper' component on the Login Screen so that the appearance is consistent with Safari and Chrome.

Fix firefox css issues

---

package-lock.json
package.json

Bump twilio-video to 2.4.0

---

src/utils.ts

- N/A
Fixes an issue found by @danionescu in this comment: https://github.com/twilio/twilio-video-app-react/commit/1aa65abecbcf90a69bc3472b28edc277a8d95983#r38961723

Return promise inside ensureMediaPermissions

---

src/components/MenuBar/ToggleFullScreenButton/ToggleFullScreenButton.test.tsx
src/components/MenuBar/ToggleFullScreenButton/ToggleFullScreenButton.tsx
src/setupTests.ts

- N/A
This PR adds a check to the FullScreen button so that it doesn't render when the FullScreen API isn't supported. Resolves #206

Fix ios fullscreen

---

package-lock.json
package.json

Update twilio-video sdk to 2.5.0

---

src/components/MenuBar/MenuBar.test.tsx
src/components/MenuBar/MenuBar.tsx
src/components/VideoProvider/index.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts

- [AHOYAPPS-707](https://issues.corp.twilio.com/browse/AHOYAPPS-707)
This PR disabled the Join Room button while the `getUserMedia` promise is pending. I user must allow or deny camera & microphone permissions before they are allowed to join the room.
Resolves #201 
Resolves #220

Disable Join Room button while media permissions are pending

---

src/components/VideoProvider/index.tsx
src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
src/hooks/useLocalVideoToggle/useLocalVideoToggle.tsx

Remove videoTrack from state when muted

---

package-lock.json
package.json
src/types.ts

N/A
This PR upgrades twilio-video and @types/twilio-video. It also resolves a type conflict with @types/twilio-video and the `src/types.ts` file. Also, `npm audit` was run which resolves the npm warning about 5000+ packages having low severity vulnerabilities.

Upgrade twilio video

---

src/components/MenuBar/AboutDialog/AboutDialog.test.tsx
src/components/MenuBar/AboutDialog/AboutDialog.tsx
src/components/VideoProvider/useRoom/useRoom.tsx
src/index.tsx
src/state/index.tsx
src/state/usePasscodeAuth/usePasscodeAuth.test.tsx
src/state/usePasscodeAuth/usePasscodeAuth.ts
src/types.ts
src/utils/useConnectionOptions/useConnectionOptions.test.tsx
src/utils/useConnectionOptions/useConnectionOptions.ts

- [AHOYAPPS-828](https://issues.corp.twilio.com/browse/AHOYAPPS-828)
This PR changes the Passcode variant of the app to work with a new version of the [RTC plugin](https://github.com/twilio-labs/plugin-rtc/pull/40). This new version of the CLI Plugin will use the Rooms API to create rooms of a specific type. The `/token` endpoint created by the CLI plugin will now contain a field for `room_type` in its response. The passcode variant of the video app will use this `room_type` parameter to disable simulcast when the room type is peer-to-peer.

Optimize for p2p

---

README.md

Update readme section about pricing

Update readme section about pricing

---

package-lock.json
package.json

Upgrade twilio-video to 2.9.0

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR updates the changelog for version 0.2.2. View changelog here: https://github.com/twilio/twilio-video-app-react/blob/release-0.2.2/CHANGELOG.md

Release 0.2.2

---

CHANGELOG.md
package-lock.json
package.json

release 0.2.3

---

README.md
src/utils/useConnectionOptions/useConnectionOptions.ts

https://issues.corp.twilio.com/browse/VIDEO-4495

VIDEO-4495 | Update to latest CDN

---

CHANGELOG.md
README.md
package-lock.json
package.json

- N/A
This PR prepares the release of version 0.3.0 of the app by incrementing the version and updating the changelog.

Release 0.3.0

---

server/createExpressHandler.ts
src/utils/useConnectionOptions/useConnectionOptions.ts

Add ability to change twilio environments

---

.circleci/config.yml
cypress/integration/twilio-video.spec.js
src/components/MainParticipantInfo/MainParticipantInfo.tsx
src/components/MenuBar/Menu/Menu.tsx

- [VIDEO-4885](https://issues.corp.twilio.com/browse/VIDEO-4885)
This PR adds cypress tests for the recording start/stop feature.

Video 4885 recording cypress tests

---

.circleci/config.yml

- N/A
This PR adds a step to the 'deploy' pipeline. It saves the json file that is needed by the server to authenticate firebase users.

Save firebase admin credentials when deploying in circle

---

CHANGELOG.md
README.md

Readme and changelog for recording start-stop feature

readme and changelog for recording start stop feature

---

.circleci/config.yml
.gcloudignore

Update circleci config

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR prepares the release of version 0.4.1 of the app. I added a `Thanks!` section for the users that had their PRs merged. Let me know if I should change it to something like "Thanks to the community". See updated changelog here:
https://github.com/twilio/twilio-video-app-react/blob/f6e45c5ebb414a81d4327f0b00a2f4342da7371b/CHANGELOG.md

Release 0.4.1

---

package-lock.json
package.json
src/components/AudioTrack/AudioTrack.test.tsx
src/components/AudioTrack/AudioTrack.tsx
src/components/VideoTrack/VideoTrack.test.tsx
src/components/VideoTrack/VideoTrack.tsx

Fix Chrome 92 WebMediaPlayer issue

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR prepares the release of version 0.4.2 of the app.

Release version 0.4.2

---

package-lock.json
package.json

- [VIDEO-6399](https://issues.corp.twilio.com/browse/VIDEO-6399)
Update the twilio-video sdk

VIDEO-6399 | Update twilio-video sdk

---

CHANGELOG.md

update changelog with correct date

---

package-lock.json
package.json

- N/A
Updates twilio-video to version 2.17.1

Upgrade twilio-video to version 2.17.1

---

package-lock.json
package.json
src/components/MenuBar/Menu/Menu.test.tsx
src/components/MenuBar/Menu/Menu.tsx
src/components/VideoProvider/useRoom/useRoom.tsx

- N/A
This PR adds a button to the menu to toggle the Video Room Monitor. The button is only visible on desktop.

Add Video Room Monitor to app

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR prepares the release of version 0.6.0 of the app.

Bump version and update changelog

---

CHANGELOG.md
package-lock.json
package.json
src/components/MenuBar/Menu/Menu.tsx

Prepare 0.6.1 release
- N/A
This PR updates the `twilio-video` and `@twilio/video-room-monitor` packages and releases version 0.6.1.

Update packages and changelog

---

CHANGELOG.md
package-lock.json
package.json
src/utils/useConnectionOptions/useConnectionOptions.test.tsx
src/utils/useConnectionOptions/useConnectionOptions.ts

Add adaptive simulcast

---

CHANGELOG.md
package-lock.json
package.json
server/index.ts

N/A
This PR:
- Updates twilio-video to the most recent version
- Fixes an issue in the local server that was causing index.html to be erroneously cached. Now, index.html will never be cached by browsers, which is the expected behavior.

Update video sdk

---

CHANGELOG.md
package-lock.json
package.json

- N/A
This PR updates the twilio-video version, which adds support for iOS WebViews. It also adds a changelog entry and bumps the app version in preparation for a new release.
See changelog: https://github.com/twilio/twilio-video-app-react/blob/release-new-video-sdk-version/CHANGELOG.md

Release new video sdk version

---

CHANGELOG.md
package-lock.json
package.json
src/components/ErrorDialog/ErrorDialog.test.tsx
src/components/ErrorDialog/enhanceMessage.ts
src/components/VideoProvider/useRoom/useRoom.tsx
src/components/VideoProvider/useScreenShareToggle/useScreenShareToggle.tsx

- N/A
This PR updates the twilio-video version and prepares the app version and changelog for a release. It also increases the maxListeners for the room object to resolve an internal ticket: https://issues.corp.twilio.com/browse/VIDEO-9156
See Changelog: https://github.com/twilio/twilio-video-app-react/blob/prep-release-0.6.5/CHANGELOG.md

Prepare release of version 0.6.5

---

app.yaml
src/hooks/usePresentationParticipants/usePresentationParticipants.test.tsx
src/hooks/usePresentationParticipants/usePresentationParticipants.tsx

Grid mode bugfix

---

src/components/VideoProvider/useScreenShareToggle/useScreenShareToggle.tsx

This PR removes constraints when requesting a screen share track. Removing the frame rate and resolution constraints should allow for higher quality screen share tracks to be published.

Remove additional constraints when requesting screen share track

---

src/components/GalleryView/__snapshots__/GalleryView.test.tsx.snap
src/components/MobileGalleryView/__snapshots__/MobileGalleryView.test.tsx.snap
src/components/Participant/Participant.tsx
src/components/ParticipantList/ParticipantList.test.tsx
src/components/ParticipantList/__snapshots__/ParticipantList.test.tsx.snap
src/components/VideoProvider/index.test.tsx
src/components/VideoProvider/useSelectedParticipant/useSelectedParticipant.test.tsx
src/components/VideoProvider/useSelectedParticipant/useSelectedParticipant.tsx

This PR ensures that "pinned" participants are unselected when switching to Gallery View. It also memoizes the  `<Participant />` component to fix a flicker bug on iOS mobile

Pinned participant fix

---

CHANGELOG.md
package-lock.json
package.json

Release 0.7.1

---

CHANGELOG.md
package-lock.json
package.json

Updating twilio-video to 2.25.0.

---

package-lock.json

- [VIDEO-12277](https://issues.corp.twilio.com/browse/VIDEO-12277)
This PR updates `package-lock.json` to remove the most critical dependency vulnerabilities. When you run `npm audit` on this branch, you no longer see the critical vulnerabilities mentioned in #776 .

VIDEO-12277 Fixing some security vulnerabilities

---

package-lock.json
package.json

Bumping version to 0.10.0.

---

CHANGELOG.md
package-lock.json
package.json

Fix error in the deploy CircleCI job.

---

README.md

Update README.md with Twilio Video EOL banner

Update README.md with Twilio Video EOL banner

---

README.md

Updates to the Video EOL notices to detail the extension to Dec 5, 2026

Updated the EOL notice

---

README.md

- [VBLOCKS-3645](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3645)
Removing legacy Room types.

Removing legacy Room types

---

CHANGELOG.md
server/__tests__/createExpressHandler.test.ts
server/createExpressHandler.ts

Change roomType to p2p

---

.circleci/config.yml

Temporarily disable cypress

---

.circleci/config.yml
CHANGELOG.md
server/__tests__/createExpressHandler.test.ts
server/createExpressHandler.ts

Undoing the last two commits for testing

Change default room type back to group rooms
